In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


749 μs ± 37.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
31.4 ms ± 1.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6]])
print(data)




[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6. ]]


In [4]:
data_0 = data * 10
print(data_0)

data_1 = data + data
print(data_1)

data_2 = data * data
print(data_2)

dataShape = data.shape
print(dataShape)

dataDtype = data.dtype
print(dataDtype)

[[ 15.  -1.  30.]
 [  0. -30.  60.]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  12. ]]
[[2.25e+00 1.00e-02 9.00e+00]
 [0.00e+00 9.00e+00 3.60e+01]]
(2, 3)
float64


In [5]:
import numpy as np
data_3 = [[[1.1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

arr2 = np.array(data_3)
print(arr2)

print(arr2.ndim)

print(arr2.shape)

print(arr2.size)

print(arr2.dtype)

[[[ 1.1  2.   3.   4. ]
  [ 5.   6.   7.   8. ]
  [ 9.  10.  11.  12. ]]

 [[13.  14.  15.  16. ]
  [17.  18.  19.  20. ]
  [21.  22.  23.  24. ]]]
3
(2, 3, 4)
24
float64


In [6]:
import numpy as np
arrZero = np.zeros(10)
print(f"arrZero: {arrZero}\n")

arrZero1 = np.zeros((3,6))
print(f"arrZero1: {arrZero1}\n")

arrEmpty = np.empty((2,3,2))
print(f"arrEmpty: {arrEmpty}\n")

arrOnes = np.ones((3,4))
print(f"arrOnes: {arrOnes}\n")

arrZero: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

arrZero1: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

arrEmpty: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

arrOnes: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [10]:
import numpy as np

arrArange = np.arange(15)
print(f"arrArange: {arrArange}\n")

arrArange1 = np.arange(15).reshape(3,5)
print(f"arrArange1: {arrArange1}\n")

print(f"arrArange1.dtype: {arrArange1.dtype}\n")

float_arr = arrArange1.astype(np.float64)
print(f"float_arr: {float_arr}\n")

print(f"float_arr.dtype: {float_arr.dtype}\n")

float_arr1 = np.array([1.2, 2.3, 3.4])
int_arr = float_arr1.astype(np.int32)
print(f"int_arr: {int_arr}\n")

print(f"int_arr.dtype: {int_arr.dtype}\n")

arrArange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

arrArange1: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

arrArange1.dtype: int64

float_arr: [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

float_arr.dtype: float64

int_arr: [1 2 3]

int_arr.dtype: int32



In [12]:
import numpy as np

int_arr = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50, .546, .577, .60, .635], dtype=np.float64)

print(f"int_arr.astype(calibers.dtype): {int_arr.astype(calibers.dtype)}\n")

zeros_uint32 = np.zeros(8, dtype="u4")
print(f"zeros_uint32: {zeros_uint32}\n")

int_arr.astype(calibers.dtype): [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

zeros_uint32: [0 0 0 0 0 0 0 0]



In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arrMulti = arr * arr

arrminus = arr - arr

print(f"arrMulti: {arrMulti}\n")

print(f"arrminus: {arrminus}\n")

arr1 = 1 / arr

print(f"arr1: {arr1}\n")

arr2 = arr ** 3

print(f"arr2: {arr2}\n")

arr3 = np.array([[0., 4., 1.], [7., 2., 12.]])

print(f"arr > arr3: {arr > arr3}\n")


arrMulti: [[ 1  4  9]
 [16 25 36]]

arrminus: [[0 0 0]
 [0 0 0]]

arr1: [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

arr2: [[  1   8  27]
 [ 64 125 216]]

arr > arr3: [[ True False  True]
 [False  True False]]



In [15]:
import numpy as np

arr = np.arange(10)

print(f"arr: {arr}\n")

arrIndex5 = arr[5]

print(f"arrIndex5: {arrIndex5}\n")

arrIndex5_8 = arr[5:8]

print(f"arrIndex5_8: {arrIndex5_8}\n")

arrIndex5_8[0] = 99

print(f"arr: {arr}\n")


arr: [0 1 2 3 4 5 6 7 8 9]

arrIndex5: 5

arrIndex5_8: [5 6 7]

arr: [ 0  1  2  3  4 99  6  7  8  9]



In [18]:
import numpy as np

arr2x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"arr2x3[2]: {arr2x3[0]}\n")

print(f"arr2x3[1][2]: {arr2x3[1][2]}\n")

print(f"arr2x3[1, 2]: {arr2x3[1, 2]}\n")

arr2x3[2]: [1 2 3]

arr2x3[1][2]: 6

arr2x3[1, 2]: 6



In [11]:
import numpy as np

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(f"arr3d[0]: {arr3d[0]}\n")

print(f"arr3d[1][0]: {arr3d[1][0]}\n")

print(f"arr3d[1, 0, 2]: {arr3d[1, 0, 2]}\n")

old_values = arr3d[0].copy()

arr3d[0] = 42

print(f"arr3d[0]: {arr3d[0]}\n")

arr3d[0] = old_values

print(f"arr3d[0]: {arr3d[0]}\n")

arrSlice1 = arr3d[1, :, :]

print(f"arrSlice1: {arrSlice1}\n")

arrSlice2 = arr3d[1, :, 2]

print(f"arrSlice2: {arrSlice2}\n")

arrSlice3 = arr3d[1, 1, :]

print(f"arrSlice3: {arrSlice3}\n")

arrSlice4 = arr3d[:1, :2, 1:]

print(f"arrSlice4: {arrSlice4}\n")

arr3d[0]: [[1 2 3]
 [4 5 6]]

arr3d[1][0]: [7 8 9]

arr3d[1, 0, 2]: 9

arr3d[0]: [[42 42 42]
 [42 42 42]]

arr3d[0]: [[1 2 3]
 [4 5 6]]

arrSlice1: [[ 7  8  9]
 [10 11 12]]

arrSlice2: [ 9 12]

arrSlice3: [10 11 12]

arrSlice4: [[[2 3]
  [5 6]]]



In [12]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.array([[1.4, 7.1, -1.2, 3.4], [1.6, -2.4, 2.7, -3.2], [-1.4, 4.3, -1.9, -2.8], [-1.4, 4.3, -1.9, -2.8], [-1.4, 4.3, -1.9, -2.8], [-1.4, 4.3, -1.9, -2.8], [-1.4, 4.3, -1.9, -2.8]])

print(f"names == 'Bob': {names == 'Bob'}\n")

print(f"data[names == 'Bob']:\n{data[names == 'Bob']}\n")



names == 'Bob': [ True False False  True False False False]

data[names == 'Bob']:
[[ 1.4  7.1 -1.2  3.4]
 [-1.4  4.3 -1.9 -2.8]]



In [28]:
# fancy indexing

import numpy as np

arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
    
arr1 = arr[[4, 3, 0, 6]]

print(f"arr1: {arr1}\n")

arr2 = arr[[-3, -5, -7]]

print(f"arr2: {arr2}\n")

arr = np.arange(32).reshape((8, 4))

print(f"arr: {arr}\n")

rows = [0, 2, 3]

subA = arr[rows, :]

print(f"subA: {subA}\n")

cols = [1, 3, 2]

subB = arr[:, cols]

print(f"subB: {subB}\n")

subC = arr[rows, cols]

print(f"subC: {subC}\n")

arr1: [[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]

arr2: [[5. 5. 5. 5.]
 [3. 3. 3. 3.]
 [1. 1. 1. 1.]]

arr: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

subA: [[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

subB: [[ 1  3  2]
 [ 5  7  6]
 [ 9 11 10]
 [13 15 14]
 [17 19 18]
 [21 23 22]
 [25 27 26]
 [29 31 30]]

subC: [ 1 11 14]



In [29]:
# Transposing arrays and swapping axes
import numpy as np

arr = np.arange(15).reshape((3, 5))

print(f"arr: {arr}\n")

arrTranspose = arr.T

print(f"arrTranspose: {arrTranspose}\n")





arr: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

arrTranspose: [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]

