In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


749 μs ± 37.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
31.4 ms ± 1.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6]])
print(data)




[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6. ]]


In [4]:
data_0 = data * 10
print(data_0)

data_1 = data + data
print(data_1)

data_2 = data * data
print(data_2)

dataShape = data.shape
print(dataShape)

dataDtype = data.dtype
print(dataDtype)

[[ 15.  -1.  30.]
 [  0. -30.  60.]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  12. ]]
[[2.25e+00 1.00e-02 9.00e+00]
 [0.00e+00 9.00e+00 3.60e+01]]
(2, 3)
float64


In [5]:
import numpy as np
data_3 = [[[1.1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]]

arr2 = np.array(data_3)
print(arr2)

print(arr2.ndim)

print(arr2.shape)

print(arr2.size)

print(arr2.dtype)

[[[ 1.1  2.   3.   4. ]
  [ 5.   6.   7.   8. ]
  [ 9.  10.  11.  12. ]]

 [[13.  14.  15.  16. ]
  [17.  18.  19.  20. ]
  [21.  22.  23.  24. ]]]
3
(2, 3, 4)
24
float64


In [6]:
import numpy as np
arrZero = np.zeros(10)
print(f"arrZero: {arrZero}\n")

arrZero1 = np.zeros((3,6))
print(f"arrZero1: {arrZero1}\n")

arrEmpty = np.empty((2,3,2))
print(f"arrEmpty: {arrEmpty}\n")

arrOnes = np.ones((3,4))
print(f"arrOnes: {arrOnes}\n")

arrZero: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

arrZero1: [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

arrEmpty: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]

arrOnes: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [10]:
import numpy as np

arrArange = np.arange(15)
print(f"arrArange: {arrArange}\n")

arrArange1 = np.arange(15).reshape(3,5)
print(f"arrArange1: {arrArange1}\n")

print(f"arrArange1.dtype: {arrArange1.dtype}\n")

float_arr = arrArange1.astype(np.float64)
print(f"float_arr: {float_arr}\n")

print(f"float_arr.dtype: {float_arr.dtype}\n")

float_arr1 = np.array([1.2, 2.3, 3.4])
int_arr = float_arr1.astype(np.int32)
print(f"int_arr: {int_arr}\n")

print(f"int_arr.dtype: {int_arr.dtype}\n")

arrArange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

arrArange1: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

arrArange1.dtype: int64

float_arr: [[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]]

float_arr.dtype: float64

int_arr: [1 2 3]

int_arr.dtype: int32



In [12]:
import numpy as np

int_arr = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50, .546, .577, .60, .635], dtype=np.float64)

print(f"int_arr.astype(calibers.dtype): {int_arr.astype(calibers.dtype)}\n")

zeros_uint32 = np.zeros(8, dtype="u4")
print(f"zeros_uint32: {zeros_uint32}\n")

int_arr.astype(calibers.dtype): [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

zeros_uint32: [0 0 0 0 0 0 0 0]

