In [2]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]


738 μs ± 16.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
31.2 ms ± 1.94 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [3]:
data = np.array([[1.5, -0.1, 3], [0, -3, 6]])
print(data)




[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6. ]]


In [6]:
data_0 = data * 10
print(data_0)

data_1 = data + data
print(data_1)

data_2 = data * data
print(data_2)

dataShape = data.shape
print(dataShape)

dataDtype = data.dtype
print(dataDtype)





[[ 15.  -1.  30.]
 [  0. -30.  60.]]
[[ 3.  -0.2  6. ]
 [ 0.  -6.  12. ]]
[[2.25e+00 1.00e-02 9.00e+00]
 [0.00e+00 9.00e+00 3.60e+01]]
(2, 3)
float64
